import {Inter} from "next/font/google"
import "./globals.css";
import NavigationBar from "@/components/frontend/layout/NavigationBar";
import Footer from "@/components/frontend/layout/Footer";
import ToastProvider from "@/components/frontend/wrapper/ToastProvider";
const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: "business solution",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}`}>
        <NavigationBar/>
        <main className="min-h-screen">{children}</main>
        <ToastProvider/>
        <Footer/>
      </body>
    </html>
  );
}
